diode:
  config:
    output_type: otlp
    output_path: "127.0.0.1:4317"
  policies:      
    discovery_1:
      kind: discovery
      backend: suzieq
      data:     
        inventory: 
          sources:
            - name: default_inventory
              hosts:
                - url: ssh://networklab.ops.orb.live:2021 username=root password=nEtb0xL4bS2023
          devices:
            - name: default_devices
              transport: ssh
              ignore-known-hosts: true
              slow-host: true
          namespaces:
            - name: default_namespace
              source: default_inventory
              device: default_devices
